### ISSUE TITLE
[BUG] [Stack Three Columns] Background is white whenusing a dark theme in Firefox + GM

### ISSUE THREAD

**Issue by PurpleMagick** [CertainPerformance/Stack-Exchange-Userscripts#12]
**Which userscript**
Stack Three Columns

**Describe the bug**
When using Greasemonkey and the dark theme for Stack Overflow, the three column edit view that opens has a white background which makes many elements hard to read.

**To Reproduce**
Steps to reproduce the behaviour:
1. Change the Stack Overflow theme to Dark [direct link](https://stackoverflow.com/users/preferences/).
2. On the URL [https://stackoverflow.com/q/11227809/](https://stackoverflow.com/q/11227809/).
3. Click on on the **edit** link on any post, for example the question.
4. The background of the three panels is white instead of dark like the rest of the site.

[Screenshot](https://i.imgur.com/NG38GNM.png)

**Expected behavior**
The three column layout to be dark. Preferably recognising the theme used the site.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Browser Version: 77
 - Userscript Manager: Greasemonkey

**Additional context**

The issue is somehow connected with how Greasemonkey handles the script. Most likely something to do with the isolation it applies. The issue doesn't show up in Tampermonkey (tested in ChromeVersion 75) nor in Violentmonkey (tested in Firefox 77).

The script is using `background-color: var(--white);` [here ](https://github.com/CertainPerformance/Stack-Exchange-Userscripts/blob/master/Three-Columns/src/styleText.scss#L50) . This matches the declaration the following rule from **primary.css**:

```css
body {
 min-height:100%;
 display:flex;
 flex-direction:column;
 background-color:var(--white);
 /* truncated the rest for brevity */
}
```
Where the the `--white`  is defined in **stacks.css**:

```css
body.theme-dark {
 --white:#2d2d2d;
 --black:#fff;
 /* truncated the rest for brevity */
}
```
So, the `--white` should work and it does in other userscript managers, however GM has a different handling of styles from the userscript with regards to styles on the main site.

I don't know if there is an easy fix for this. My current workaround is to just use Violentmonkey for this script
