### ISSUE TITLE
Paragraph Spacing rule is incomplete (Compact Line Height.js)

### ISSUE THREAD

**Issue by Prid13** [CertainPerformance/Stack-Exchange-Userscripts#14]
The code to rectify paragraph spacing in your [compact line height script](https://github.com/CertainPerformance/Stack-Exchange-Userscripts/blob/master/Compact-Line-Height/StackCompactLineHeight.user.js) is incomplete:

```css
/* Spacing between paragraphs: */
.s-prose p {
    /* 15px (equal to 1em) was the old margin-bottom, 1.4em (equal to 21px); is the new margin-bottom */
    margin-bottom: 15px !important;
}
```

Tried using it in my Chrome extension, but noticed a lot of weird spacing. Compared a lot with the old formatting and discovered some things:

- `<p>` tags inside `<blockquote>` also get the `margin-bottom` from `.s-prose p`, which is good. But the last element's margin-bottom needs to be `0px`, otherwise the bottom part of blockquote looks uneven
- `1em` translates to different `px` values depending on element. Headings are specifically affected by this, because of their varying `font-size`
- other elements have different margin-bottom values, like `<pre>` and `<li>`

Here's the code I landed on in the end:

```css
/* old paragraph spacing */
.s-prose p, .s-prose ol, .s-prose ul, .s-prose blockquote, .s-prose hr {
  margin-bottom: 15px!important;
}

.s-prose pre {
  margin-bottom: 13px!important;
}

.s-prose ol li, .s-prose ul li {
  margin-bottom: 7.5px!important;
}

.s-prose ol li:last-child, .s-prose ul li:last-child {
  margin-bottom: 0!important;
}

.s-prose h1 { margin-bottom: 21px!important; }
.s-prose h2 { margin-bottom: 19px!important; }
.s-prose h3 { margin-bottom: 17px!important; }
.s-prose h4 { margin-bottom: 15px!important; }

.s-prose blockquote *:last-child {
  margin-bottom: 0!important;
}
```

There are some more edge cases with last elements inside lists, etc., but they're not apparent so I skipped them for now.

Hope this helps :)
